/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.remgant.app;

import net.remgant.list.LinkedList;

import static net.remgant.utilities.StringUtils.join;
import static net.remgant.utilities.StringUtils.split;
import static net.remgant.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
